//! 此文件由 build.rs 自动生成，请勿手动修改
//! Auto-generated by build.rs, DO NOT EDIT

use anyhow::Result;
use clap::Subcommand;
use clap_complete::aot::Shell;

pub mod agentx;
pub mod basex;
pub mod basic;
pub mod encrypt;
pub mod fastcgi;
pub mod githack;
pub mod gopher;
pub mod hash;
pub mod hashpow;
pub mod image;
pub mod jwttool;
pub mod parser;
pub mod qrcode;
pub mod sitemap;
pub mod terminal;
pub mod timestamp;
pub mod wechat;

use crate::{core::external,Action};

#[derive(Subcommand)]
pub enum Command {
    /// External command
    #[clap(external_subcommand)]
    External(Vec<String>),

    /// Shell completion scripts
    #[clap(alias = "comp")]
    Completion {
        #[arg(help = "shell type")]
        shell: Option<Shell>,
    },

    /// Download and manage agent skills
    #[clap(alias = "ax")]
    Agentx(agentx::Cmd),

    /// Base encoding/decoding tools (base16/32/36/58/62/64/91/100)
    #[clap(alias = "bx")]
    Basex(basex::Cmd),

    /// Basic utils tools (URL, String, Bin, XOR, Random)
    Basic(basic::Cmd),

    /// File encryption with AES-CTR
    #[clap(alias = "enc")]
    Encrypt(encrypt::Cmd),

    /// FastCGI protocol record generator
    #[clap(alias = "fcgi")]
    Fastcgi(fastcgi::Cmd),

    /// A .git folder disclosure exploit tool
    #[clap(alias = "gh")]
    Githack(githack::Cmd),

    /// Generate Gopher SSRF payload
    #[clap(alias = "gop")]
    Gopher(gopher::Cmd),

    /// Hash functions (MD2/4/5, SHA1/2/3, RIPEMD160, bcrypt, MySQL, NTLM)
    Hash(hash::Cmd),

    /// Hash Power of Work brute force (MD5/SHA1)
    #[clap(alias = "pow")]
    Hashpow(hashpow::Cmd),

    /// Image processing tools (convert, resize, icon, exif)
    #[clap(alias = "img")]
    Image(image::Cmd),

    /// JWT tool with Print/Crack/Modify/Create
    #[clap(alias = "jwt")]
    Jwttool(jwttool::Cmd),

    /// Parse various file formats (DS_Store, /proc/net)
    Parser(parser::Cmd),

    /// QR code generate and parse tools
    #[clap(alias = "qr")]
    Qrcode(qrcode::Cmd),

    /// Generate sitemap.xml with given URLs
    #[clap(alias = "sm")]
    Sitemap(sitemap::Cmd),

    /// Terminal environment helpers
    #[clap(alias = "term")]
    Terminal(terminal::Cmd),

    /// Print or parse timestamps
    #[clap(alias = "ts")]
    Timestamp(timestamp::Cmd),

    /// Decrypt Wechat DB files
    #[clap(alias = "vx")]
    Wechat(wechat::Cmd),
}

impl Command {
    pub async fn invoke(&self) -> Result<()> {
        match self {
            Command::External(args) => external(args),
            Command::Agentx(c) => c.execute().await,
            Command::Basex(c) => c.execute().await,
            Command::Basic(c) => c.execute().await,
            Command::Encrypt(c) => c.execute().await,
            Command::Fastcgi(c) => c.execute().await,
            Command::Githack(c) => c.execute().await,
            Command::Gopher(c) => c.execute().await,
            Command::Hash(c) => c.execute().await,
            Command::Hashpow(c) => c.execute().await,
            Command::Image(c) => c.execute().await,
            Command::Jwttool(c) => c.execute().await,
            Command::Parser(c) => c.execute().await,
            Command::Qrcode(c) => c.execute().await,
            Command::Sitemap(c) => c.execute().await,
            Command::Terminal(c) => c.execute().await,
            Command::Timestamp(c) => c.execute().await,
            Command::Wechat(c) => c.execute().await,
            _ => Err(anyhow::anyhow!("Unknown command")),
        }
    }
}
