use std::env;
use std::fs::{self, File};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

#[derive(Debug, Clone)]
struct CmdConfig {
    mod_name: String,
    crate_name: String,
    cmd_name: String,
    aliases: Vec<String>,
    about: String,
}

fn has_cmd_struct(mod_rs_path: &Path) -> bool {
    let content = fs::read_to_string(mod_rs_path).unwrap_or_default();
    content.contains("pub struct Cmd")
}

fn parse_cmd_config(dir_name: &str, mod_rs_path: &Path) -> Option<CmdConfig> {
    if !has_cmd_struct(mod_rs_path) {
        return None;
    }
    if !dir_name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_')
    {
        return None;
    }

    let file = File::open(mod_rs_path).ok()?;
    let reader = BufReader::new(file);

    let mut aliases = Vec::new();
    let mut about = String::new();

    for line in reader.lines() {
        let line = line.ok()?;
        let trimmed = line.trim();

        if trimmed.starts_with("//! @alias:") {
            let alias = trimmed.trim_start_matches("//! @alias:").trim();
            if !alias.is_empty() {
                aliases.push(alias.to_string());
            }
        } else if trimmed.starts_with("//! @about:") {
            about = trimmed.trim_start_matches("//! @about:").trim().to_string();
        }
    }

    let cmd_name = dir_name
        .split('_')
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().chain(c).collect(),
            }
        })
        .collect::<String>();

    if about.is_empty() {
        about = format!("{cmd_name} command");
    }

    Some(CmdConfig {
        mod_name: dir_name.to_string(),
        crate_name: format!("enyo_cmd_{dir_name}"),
        cmd_name,
        aliases,
        about,
    })
}

fn scan_cmds_dir(modules_dir: &Path) -> Vec<CmdConfig> {
    let mut configs = Vec::new();

    if let Ok(entries) = fs::read_dir(modules_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }

            let dir_name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
            let mod_rs = path.join("src/mod.rs");
            if mod_rs.exists() {
                if let Some(config) = parse_cmd_config(dir_name, &mod_rs) {
                    configs.push(config);
                }
            }
        }
    }

    configs.sort_by(|a, b| a.mod_name.cmp(&b.mod_name));
    configs
}

fn generate_crate_imports(configs: &[CmdConfig]) -> String {
    configs
        .iter()
        .map(|c| format!("use {} as {};", c.crate_name, c.mod_name))
        .collect::<Vec<_>>()
        .join("\n")
}

fn generate_enum_variants(configs: &[CmdConfig]) -> String {
    configs
        .iter()
        .map(|c| {
            let attrs = c
                .aliases
                .iter()
                .map(|alias| format!("alias = \"{alias}\""))
                .collect::<Vec<_>>();

            let clap_attr = if attrs.is_empty() {
                String::new()
            } else {
                format!("    #[clap({})]\n", attrs.join(", "))
            };

            format!(
                "    /// {}\n{}    {}({}::Cmd),",
                c.about, clap_attr, c.cmd_name, c.mod_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn generate_match_arms(configs: &[CmdConfig]) -> String {
    configs
        .iter()
        .map(|c| {
            format!(
                "            Command::{}(c) => c.execute().await,",
                c.cmd_name
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn main() {
    println!(
        "cargo:rustc-env=CARGO_PKG_VERSION={}",
        env!("CARGO_PKG_VERSION")
    );

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_dir = Path::new(&manifest_dir)
        .parent()
        .and_then(Path::parent)
        .expect("workspace directory");
    let cmds_dir = workspace_dir.join("crates");
    let mod_rs_path = Path::new(&manifest_dir).join("src/cmds.rs");

    println!("cargo:rerun-if-changed={}", cmds_dir.to_string_lossy());

    let cmds = scan_cmds_dir(&cmds_dir);
    for cmd in &cmds {
        println!(
            "cargo:rerun-if-changed={}/src/mod.rs",
            cmds_dir.join(&cmd.mod_name).to_string_lossy()
        );
    }

    let crate_imports = generate_crate_imports(&cmds);
    let enum_variants = generate_enum_variants(&cmds);
    let match_arms = generate_match_arms(&cmds);

    let generated_code = format!(
        r#"//! 此文件由 build.rs 自动生成，请勿手动修改
//! Auto-generated by build.rs, DO NOT EDIT

use anyhow::Result;
use clap::Subcommand;
use clap_complete::aot::Shell;

{crate_imports}

use enyo_core::{{core::external, Action}};

#[derive(Subcommand)]
pub enum Command {{
    /// External command
    #[clap(external_subcommand)]
    External(Vec<String>),

    /// Shell completion scripts
    #[clap(alias = "comp")]
    Completion {{
        #[arg(help = "shell type")]
        shell: Option<Shell>,
    }},

{enum_variants}
}}

impl Command {{
    pub async fn invoke(&self) -> Result<()> {{
        match self {{
            Command::External(args) => external(args),
{match_arms}
            _ => Err(anyhow::anyhow!("Unknown command")),
        }}
    }}
}}
"#
    );

    let existing_content = fs::read_to_string(&mod_rs_path).unwrap_or_default();
    if existing_content != generated_code {
        let mut f = File::create(&mod_rs_path).unwrap();
        f.write_all(generated_code.as_bytes()).unwrap();
        println!("cargo:warning=Generated crates/enyo/src/cmds.rs");
    }
}
